#sudo: required

os:
  - linux
  - osx

osx_image: xcode8.2

#dist: xerus - no Ubuntu 16 on travis-cl
dist: trusty

compiler:
 - gcc
 - clang

script:
 - mkdir -p TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build && cmake .. && cmake --build .
